#!/usr/bin/env python3
"""rtflood - Roughtime load testing tool optimized for high packet rate.

Each packet is sent on a separate UDP socket, which is closed immediately after sending.
The payload is static and hardcoded for predictable packet contents.

(c) 2026 Viktor Pavlovic, licensed under MIT License

"""

import argparse
import os
import socket
import sys
import threading
import time
from typing import Optional, Tuple
import base64
from Cryptodome.Hash import SHA512

# This dummy message is generated by pyroughtime and corresponds to draft-12 of the Roughtime spec
PAYLOAD_PREFIX = bytes.fromhex("524f55474854494d00040000050000000400000024000000440000004800000056455200535256004e4f4e43545950455a5a5a5a0c000080")
PAYLOAD_SUFFIX = bytes.fromhex("00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000")


NONCE_SIZE = 32
DEFAULT_SNDBUF = 256 * 1024
DEFAULT_WORKERS = 16
STAT_REPORT_INTERVAL = 1.0


class Stats:
    def __init__(self) -> None:
        self.attempted = 0
        self.sent = 0
        self.failed = 0
        self.lock = threading.Lock()


def hash_key(data: bytes) -> bytes:
    """Derive the SRV tag via a SHA512 hash of the public key, truncated to first 32 bytes."""
    h = SHA512.new()
    h.update(b"\xff")
    h.update(data)
    # Note: This is NOT SHA512/256, instead the Roughtime spec only uses the first 32 bytes of the full SHA512 hash.
    return h.digest()[:32]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="High-throughput UDP packet sender with one socket per packet."
    )
    parser.add_argument("hostname", help="Target hostname or IP address")
    parser.add_argument("port", type=int, help="Target UDP port")
    parser.add_argument("public_key", type=str, help="Public key of server in base64 format")
    parser.add_argument(
        "--workers",
        type=int,
        default=DEFAULT_WORKERS,
        help=f"Number of concurrent sender threads (default: {DEFAULT_WORKERS})",
    )
    parser.add_argument(
        "--count",
        type=int,
        default=0,
        help="Total number of packets to send (0 = run until interrupted)",
    )
    parser.add_argument(
        "--duration",
        type=float,
        default=0.0,
        help="Run time in seconds (0 = no duration limit)",
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="Suppress periodic statistics output",
    )
    return parser.parse_args()


def resolve_target(hostname: str, port: int) -> Tuple[int, Tuple]:
    try:
        addr_info = socket.getaddrinfo(
            hostname,
            port,
            family=socket.AF_UNSPEC,
            type=socket.SOCK_DGRAM,
            proto=socket.IPPROTO_UDP,
        )
    except socket.gaierror as exc:
        raise RuntimeError(f"Address resolution failed for {hostname}:{port}: {exc}")

    if not addr_info:
        raise RuntimeError(f"Unable to resolve target {hostname}:{port}")

    family, _, _, _, sockaddr = addr_info[0]
    return family, sockaddr


def send_udp_packet(family: int, target: Tuple, srv_tag: bytes) -> bool:
    packet = PAYLOAD_PREFIX + srv_tag + os.urandom(NONCE_SIZE) + PAYLOAD_SUFFIX
    try:
        with socket.socket(family, socket.SOCK_DGRAM, socket.IPPROTO_UDP) as sock:
            try:
                sock.setsockopt(socket.SOL_SOCKET, socket.SO_SNDBUF, DEFAULT_SNDBUF)
            except OSError:
                pass
            sock.sendto(packet, target)
        return True
    except OSError:
        return False


def worker_loop(
    family: int,
    target: Tuple,
    stats: Stats,
    srv_tag: bytes,
    stop_event: threading.Event,
    max_packets: Optional[int],
) -> None:
    while not stop_event.is_set():
        with stats.lock:
            if max_packets is not None and stats.attempted >= max_packets:
                return
            stats.attempted += 1

        success = send_udp_packet(family, target, srv_tag)

        with stats.lock:
            if success:
                stats.sent += 1
            else:
                stats.failed += 1

        if max_packets is None and stop_event.is_set():
            return


def reporter_loop(stats: Stats, stop_event: threading.Event, start_time: float) -> None:
    last_attempted = 0
    last_time = start_time
    while not stop_event.wait(STAT_REPORT_INTERVAL):
        now = time.monotonic()
        with stats.lock:
            attempted = stats.attempted
            sent = stats.sent
            failed = stats.failed
        interval = now - last_time
        delta = attempted - last_attempted
        rate = delta / interval if interval > 0 else 0.0
        print(
            f"{attempted} packets attempted, {sent} sent, {failed} failed, "
            f"instant rate={rate:.0f} pkt/s"
        )
        last_attempted = attempted
        last_time = now


def main() -> int:
    args = parse_args()

    if args.workers <= 0:
        print("--workers must be > 0", file=sys.stderr)
        return 2

    if args.count < 0:
        print("--count must be >= 0", file=sys.stderr)
        return 2

    if args.duration < 0:
        print("--duration must be >= 0", file=sys.stderr)
        return 2

    max_packets = args.count if args.count > 0 else None
    if max_packets is None and args.duration == 0:
        print(
            "Running until interrupted. Use Ctrl+C to stop.", file=sys.stderr
        )

    try:
        family, target = resolve_target(args.hostname, args.port)
    except RuntimeError as exc:
        print(exc, file=sys.stderr)
        return 1

    srv_tag = hash_key(base64.b64decode(args.public_key))

    stats = Stats()
    stop_event = threading.Event()
    start_time = time.monotonic()

    timer: Optional[threading.Timer] = None
    if args.duration > 0:
        timer = threading.Timer(args.duration, stop_event.set)
        timer.daemon = True
        timer.start()

    worker_threads = []
    for _ in range(args.workers):
        thread = threading.Thread(
            target=worker_loop,
            args=(family, target, stats, srv_tag, stop_event, max_packets),
            daemon=True,
        )
        worker_threads.append(thread)
        thread.start()

    reporter_thread: Optional[threading.Thread] = None
    if not args.quiet:
        reporter_thread = threading.Thread(
            target=reporter_loop,
            args=(stats, stop_event, start_time),
            daemon=True,
        )
        reporter_thread.start()

    try:
        for thread in worker_threads:
            thread.join()
    except KeyboardInterrupt:
        stop_event.set()
        print("\nInterrupted, waiting for active workers to finish...", file=sys.stderr)
        for thread in worker_threads:
            thread.join()

    if timer is not None:
        timer.cancel()

    if reporter_thread is not None:
        stop_event.set()
        reporter_thread.join()

    elapsed = time.monotonic() - start_time
    with stats.lock:
        attempted = stats.attempted
        sent = stats.sent
        failed = stats.failed

    print(
        f"Finished in {elapsed:.2f}s: {attempted} packets attempted, "
        f"{sent} sent, {failed} failed, "
        f"average rate={attempted / elapsed:.0f} pkt/s"
    )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
